### ISSUE TITLE
thanks for sharing

### ISSUE THREAD

**Issue by gingerlime** [vigetlabs/ruby-string-showdown#1]
Just read your post and since I wanted to test a potential optimization, having a test harness was very useful. Thanks for sharing this.

Just a quick question: can you help interpret the output? Which numbers should I be looking at and what do they tell me?

```
Tests complete. Results:
= Variant T-Test
  Mean and standard deviation
+-----------+--------+--------+-----+
| Variable  |  mean  |   sd   |  n  |
+-----------+--------+--------+-----+
| Chained   | 0.8138 | 0.1847 | 100 |
| unchained | 0.7656 | 0.1586 | 100 |
+-----------+--------+--------+-----+

  Levene test for equality of variances : F(1, 198) = 3.5190 , p = 0.0621
  T statistics
+--------------------+--------+----------+----------------+
|        Type        |   t    |    df    | p (both tails) |
+--------------------+--------+----------+----------------+
| Equal variance     | 1.9802 | 198      | 0.0491         |
| Non equal variance | 1.9802 | 193.5647 | 0.0491         |
+--------------------+--------+----------+----------------+

  Effect size
+-------+--------+
| x1-x2 | 0.0482 |
| d     | 0.1169 |
+-------+--------+
```

**Comment by ltk** [comment]
Of course. For an optimization scenario, there's one main important number on here: the p-value (in this case `p = 0.0621`). The p-value tells you if the observed difference between your test groups is a real difference, or just the result of natural variability in your sampling. Common practice is to consider p-values of less than 0.05 as indicative of a real difference between your sample groups. (So in this case you're close to a statistically significant difference between chained and unchained, but not quite there.)

If you have a p-value of less than 0.05, then the mean values in the first table become important. The mean is the average execution time of the test you wrote, therefore the difference between them indicates how much better one group is over the other.

**Comment by gingerlime** [comment]
Thanks @ltk I really appreciate it. Sounds similar to confidence values in A/B testing...
